### ISSUE TITLE
Creating action with only 'type' rather than 'types'

### ISSUE THREAD

**Issue by oyeanuj** [jkusachi/redux-actions-api-addon#3]
Hi @jkusachi, thank you for creating this library. It seems super useful and I feel like I can reduce some clutter in my code with this. The only thing I was running into was that I have a middleware which actually appends `_SUCCESS` or `_FAILURE` according to API response. 

So, do you think it would be possible to have the `createAPIAction` accept an option in which case it only returns the passed action type as `type` rather than the triad of types that it returns today?

**Comment by jkusachi** [comment]
hey @oyeanuj  this is a great idea, and totally can happen

would you still like to see this? so sorry on delay!

**Comment by oyeanuj** [comment]
@jkusachi Thanks for responding, unfortunately, I ended up rolling my own solution to this. But I am sure someone else might find it helpful!

**Comment by jkusachi** [comment]
@oyeanuj no problem! good idea nonetheless, and one that I will look to introduce.  Thank you for your comments, much appreciated!
